using JSON, Markdown, Printf
include("../../report_layout.jl")
using .ReportLayout
const D=@__DIR__
const r=JSON.parsefile(joinpath(D,"comparison.json"))
const a=r["cases"]["factor1"]["final_hour"]
const b=r["cases"]["factor2"]["final_hour"]
const c=r["cases"]["factor3"]["final_hour"]
const d=r["cases"]["factor10"]["final_hour"]
const n=r["cases"]["historical_control"]["final_hour"]
const c8=r["cases"]["factor3"]["penultimate_hour"]
fmt(x,n=5)=@sprintf("%.*g",n,x)
change(key)=100(c[key]-a[key])/abs(a[key])
const title="Factor 3 mostly switches the closure off"
paragraphs=[
"GABLS1 factor-3 sensitivity | 22 September 2026 | 12.5 m, WENO9, one interior face, 300 s filter, 9 h, seed 123. New plots compare only factors 1 and 3, with fixed 1 m LES reference medians where available. Earlier reports and data are preserved.",
"Result: factor 3 largely switches off the added near-surface closure after spin-up, while resolved turbulence increases strongly. In 8-9 h, first-face w² rises from $(fmt(a["w2_at_12p5m"],6)) to $(fmt(c["w2_at_12p5m"],6)) m²/s², a factor of $(fmt(c["w2_at_12p5m"]/a["w2_at_12p5m"],4)). Integrated resolved TKE increases $(fmt(change("resolved_tke_vertical_integral"),4))%. First-face w³ and skewness change from negative to positive. This is a large response to the assumed missing-transport credit, not a calibrated accuracy result.",
"The intervention remains narrow: multiply signed, locally time-filtered resolved flux by three only inside max(0, 1 - a F_resolved/F_target), for momentum and heat. Aligned resolved transport reaching one-third of the target can eliminate that local deficit; countergradient transport increases it. The assumed extra transport is twice the resolved contribution. Coefficients respond dynamically; neither viscosity nor plotted covariance is simply multiplied by three.",
"Closure response: final-hour mean first-face viscosity falls from $(fmt(a["surface_layer_face1_viscosity"],6)) to $(fmt(c["surface_layer_face1_viscosity"],6)) m²/s; heat diffusivity falls from $(fmt(a["surface_layer_face1_ρθ_diffusivity"],6)) to $(fmt(c["surface_layer_face1_ρθ_diffusivity"],6)) m²/s. Factor-3 viscosity is exactly zero at $(fmt(100c["surface_layer_face1_viscosity_zero_fraction"],8))% of sampled horizontal point-times, and heat diffusivity at $(fmt(100c["surface_layer_face1_ρθ_diffusivity_zero_fraction"],8))%. The timeline shows substantial initial mixing followed by mostly inactive coefficients, with intermittent reactivation. This is a change in the closure's operating regime, not simply a small uniform reduction in its strength.",
"Fraction interpretation: each hourly value averages 60 one-minute samples over all 32×32 horizontal points. Raw zero deficit, guard-valid zero deficit and actual zero coefficient are separately retained for momentum and heat; all six fractions appear in the detailed table. All three definitions agree in the final hour. Momentum and heat guards remain valid at $(fmt(100c["surface_layer_face1_momentum_active_fraction"],7))% and $(fmt(100c["surface_layer_face1_ρθ_active_fraction"],7))%; coefficient-cap fractions are $(fmt(c["surface_layer_face1_viscosity_cap_fraction"])) and $(fmt(c["surface_layer_face1_ρθ_cap_fraction"])). Thus deficit satisfaction explains the switch-off, rather than invalid targets or active coefficient caps. Sampled zeros do not prove continuous switch-off between outputs. Factor 1 did not save these fractions; its values remain unavailable, not zero.",
"Moments and hourly sensitivity: factor-3 first-face w³ is $(fmt(c["w3_at_12p5m"],6)) m³/s³ and skewness $(fmt(c["skewness_at_12p5m"],6)); peak w² is $(fmt(c["peak_w2"],6)) and integrated resolved TKE $(fmt(c["resolved_tke_vertical_integral"],6)) m³/s². In 7-8 h, first-face w² is $(fmt(c8["w2_at_12p5m"],6)), w³ $(fmt(c8["w3_at_12p5m"],6)), skewness $(fmt(c8["skewness_at_12p5m"],6)), and integrated TKE $(fmt(c8["resolved_tke_vertical_integral"],6)). The earlier-hour zero-viscosity/zero-heat-diffusivity fractions are $(fmt(100c8["surface_layer_face1_viscosity_zero_fraction"],7))% / $(fmt(100c8["surface_layer_face1_ρθ_diffusivity_zero_fraction"],7))%. The two neighboring windows show time dependence; they do not quantify ensemble uncertainty.",
"Transport and exchange: the SGS share of first-face u-momentum covariance-plus-SGS transport falls from $(fmt(100a["sgs_signed_fraction_u_w_flux_at_12p5m"],6))% with factor 1 to $(fmt(100c["sgs_signed_fraction_u_w_flux_at_12p5m"],6))% with factor 3. Factor-3 u* is $(fmt(c["friction_velocity"],6)) m/s and sensible heat flux $(fmt(c["surface_sensible_heat_flux"],6)) W/m², versus $(fmt(a["friction_velocity"],6)) m/s and $(fmt(a["surface_sensible_heat_flux"],6)) W/m² for factor 1. Every plotted interior total is covariance plus actual constitutive SGS. It is NOT scheme-native WENO advective transport plus SGS: the numerical correction to covariance remains unmeasured. The factor experiment cannot identify or validate that missing flux.",
"Reference comparison: at native heights 0<z<=200 m, factor-3 final-hour RMS errors against the fixed 1 m LES median are $(fmt(c["u_mean_rmse_0_200m"],6)) m/s for u, $(fmt(c["theta_mean_rmse_0_200m"],6)) K for theta, and $(fmt(c["w_variance_rmse_0_200m"],6)) m²/s² for w². Changes relative to factor 1 are $(fmt(change("u_mean_rmse_0_200m"),4))%, $(fmt(change("theta_mean_rmse_0_200m"),4))%, and $(fmt(change("w_variance_rmse_0_200m"),4))%. The reference is an LES median, not observations. Greater resolved variance or a smaller mean-profile error alone does not establish faithful total transport.",
"Comparison integrity: factor 3 passed its source-specific strict admission (1 admitted, 0 rejected), with identical Breeze physics and initial native profiles, 19 exact profile times and 541 exact series times. Checksums, finite values, native vertical locations, one-face support, covariance-plus-SGS consistency and fraction bounds were verified. Factors 1/2/10 retain their original admissions. Factor 1 reproduces the corrected historical one-face300 output bit for bit; the no-closure case remains labeled as earlier-source context. The durable child record for non-login job 7348 verifies exit zero; no unavailable batch status is inferred.",
"Definitions: 8-9 h profiles average true half-hour means ending at 30600 and 32400 s; 7-8 h uses 27000 and 28800 s. Series averages exclude the hour start and include its end. Skewness is averaged w³ divided by averaged w² to the three-halves power, masked for w²<1e-6. Native model heights are retained; only the reference is interpolated for unweighted RMS errors. No scheme-native flux reconstruction, new closure design, or additional simulation is included."]
pages=textpages(title,paragraphs,"factor3",joinpath(D,"../../../work/sld/factor3/report");footer="Breeze LES evaluation | Julia | factors 1 and 3")
append!(pages,[joinpath(D,"figures/factor_profiles.pdf"),joinpath(D,"figures/factor_fluxes.pdf"),joinpath(D,"figures/factor_activity.pdf")])
run(`pdfunite $pages $(joinpath(D,"factor_results_section.pdf"))`)
open(joinpath(D,"results.md"),"w") do io
 println(io,"# ",title,"\n\n",join(paragraphs,"\n\n"))
 println(io,"\n| Final-hour quantity | Factor 1 | Factor 3 |\n|---|---:|---:|")
 for (label,key) in (("w² at 12.5 m (m²/s²)","w2_at_12p5m"),("w³ at 12.5 m (m³/s³)","w3_at_12p5m"),("Skewness at 12.5 m","skewness_at_12p5m"),("Integrated resolved TKE (m³/s²)","resolved_tke_vertical_integral"),("u* (m/s)","friction_velocity"),("Sensible heat (W/m²)","surface_sensible_heat_flux"),("First-face viscosity (m²/s)","surface_layer_face1_viscosity"),("First-face heat diffusivity (m²/s)","surface_layer_face1_ρθ_diffusivity"),("u RMS error (m/s)","u_mean_rmse_0_200m"),("theta RMS error (K)","theta_mean_rmse_0_200m"),("w² RMS error (m²/s²)","w_variance_rmse_0_200m"))
  println(io,"| ",label," | ",join([fmt(get(m,key,0.0),7) for m in (a,c)]," | ")," |")
 end
 println(io,"\n| Factor | Saved horizontal fraction | 7-8 h | 8-9 h |\n|---|---|---:|---:|")
 for factor in (3,), key in r["switch_off_series"]
  m=r["cases"]["factor$factor"]
  println(io,"| ",factor," | ",replace(key,"surface_layer_face1_"=>"")," | ",fmt(m["penultimate_hour"][key],10)," | ",fmt(m["final_hour"][key],10)," |")
 end
 println(io,"\nFractions for factor 1 are unavailable, not zero. Archived factor-2/10 and historical-control context remains in the detailed numerical comparison, not in these plots.")
 for (label,name) in (("Mean profiles and resolved moments","factor_profiles"),("Covariance plus SGS flux partition","factor_fluxes"),("Coefficient and sampled switch-off evolution","factor_activity"))
  println(io,"\n![",label,"](figures/",name,".png)")
 end
 println(io,"\n[Detailed two-hour comparison](comparison.md) · [Complete metrics and hourly fractions](comparison.json) · [Native profiles](comparison_profiles.csv) · [Julia audit](compare.jl) · [Julia plots](plot_comparison.jl) · [Strict collection](collection_v1/manifest.toml)")
 println(io,"\nSources: [Breeze 1df78f2](https://github.com/NumericalEarth/Breeze.jl/commit/1df78f2bb94db159e3a296f7439e1a5e90286014), [factor-3 evaluation b9c3102](https://github.com/glwagner/BreezeEvaluation.jl/commit/b9c31029929650c61040a5a20f9699de9a457978). Earlier exports and fixed 1 m reference data remain linked through the Julia audit.")
end
write(joinpath(D,"results.html"),"<!doctype html><meta charset=\"utf-8\"><title>GABLS1 factor3 sensitivity</title><style>body{font:18px/1.6 sans-serif;max-width:1250px;margin:40px auto;padding:0 20px}img{max-width:100%}td,th{padding:8px;text-align:left}table{border-collapse:collapse}tr{border-bottom:1px solid #ddd}</style>"*Markdown.html(Markdown.parse(read(joinpath(D,"results.md"),String))))
println("FACTOR3_REPORT_COMPLETE pages=",length(pages))
